name = "pjadvalbot"
main = "worker.js"
compatibility_date = "2024-01-01"

# تعریف پایگاه داده KV برای ذخیره‌سازی وضعیت ربات، جدول‌ها و امتیازات
kv_namespaces = [
  { binding = "CROSSWORD_KV", id = "5bdd7b937edb498eab595312cd31a043" }
]

# متغیرهای محیطی که باید از طریق Wrangler یا پنل Cloudflare مقداردهی شوند
[vars]
TELEGRAM_BOT_TOKEN = "8595424524:AAFDug-9837ATptKgJr85PwVBfIp_oKJ2ho"
ADMIN_USER_ID = "a32d6393d01843609aaf16193470dd7f"
