name = "jadvalsharh"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
ADMIN_USER_ID = "109710949"
TELEGRAM_BOT_TOKEN = "8595424524:AAEWYrIAzj6RRPWZxv-FNLoFdBiA7dEG52s"

[[kv_namespaces]]
binding = "CROSSWORD_KV"
id = "ed83c716d1b9483e8b6c5e09a7b29562"
